apiVersion: v1
kind: Service
metadata:
  name: {{ include "sipplane.fullname" . }}
  labels:
    {{- include "sipplane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "sipplane.selectorLabels" . | nindent 4 }}
  ports:
    - name: sip-udp
      port: {{ .Values.service.sipPort }}
      targetPort: sip-udp
      protocol: UDP
    - name: sip-tcp
      port: {{ .Values.service.sipPort }}
      targetPort: sip-tcp
      protocol: TCP
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
